// Test generated by RoostGPT for test roost-test using AI Model vertex

package main

import (
	"fmt"
	"math"
	"testing"
)

func TestMain818f47c3d2(t *testing.T) {
	// Test case 1: Positive change
	prevStockPrice := 80000.0
	currentStockPrice := 120000.0

	change, err := getStockPriceChange(prevStockPrice, currentStockPrice)

	if err != nil {
		t.Error(err)
	}

	if change < 0 {
		t.Errorf("Expected positive change, but got %f", change)
	} else {
		t.Logf("Change is %f", change)
	}

	// Test case 2: Negative change
	prevStockPrice = 120000.0
	currentStockPrice = 80000.0

	change, err = getStockPriceChange(prevStockPrice, currentStockPrice)

	if err != nil {
		t.Error(err)
	}

	if change > 0 {
		t.Errorf("Expected negative change, but got %f", change)
	} else {
		t.Logf("Change is %f", change)
	}
}