// Test generated by RoostGPT for test roost-test using AI Model vertex

package main

import (
	"fmt"
	"testing"
)

func TestAvg0060427098(t *testing.T) {
	// Test for two positive numbers
	x := 1.0
	y := 2.0
	expected := 1.5
	actual := avg(x, y)
	if actual != expected {
		t.Errorf("Expected %v, got %v", expected, actual)
	}

	// Test for two negative numbers
	x = -1.0
	y = -2.0
	expected = -1.5
	actual = avg(x, y)
	if actual != expected {
		t.Errorf("Expected %v, got %v", expected, actual)
	}

	// Test for one positive and one negative number
	x = 1.0
	y = -2.0
	expected = -0.5
	actual = avg(x, y)
	if actual != expected {
		t.Errorf("Expected %v, got %v", expected, actual)
	}

	// Test for two zeroes
	x = 0.0
	y = 0.0
	expected := 0.0
	actual = avg(x, y)
	if actual != expected {
		t.Errorf("Expected %v, got %v", expected, actual)
	}
}