// Test generated by RoostGPT for test roost-test using AI Model vertex

package main

import (
	"fmt"
	"math"
	"testing"
)

func TestGetNamedStockPriceChange77d6138824(t *testing.T) {
	// Test case 1: Positive change
	prevPrice := 100.0
	currentPrice := 110.0
	change, percentChange := getNamedStockPriceChange(prevPrice, currentPrice)
	if change != 10.0 {
		t.Error("Incorrect change value")
	}
	if percentChange != 10.0 {
		t.Error("Incorrect percent change value")
	}

	// Test case 2: Negative change
	prevPrice = 100.0
	currentPrice := 90.0
	change, percentChange = getNamedStockPriceChange(prevPrice, currentPrice)
	if change != -10.0 {
		t.Error("Incorrect change value")
	}
	if percentChange != -10.0 {
		t.Error("Incorrect percent change value")
	}

	// Test case 3: Zero change
	prevPrice = 100.0
	currentPrice = 100.0
	change, percentChange = getNamedStockPriceChange(prevPrice, currentPrice)
	if change != 0.0 {
		t.Error("Incorrect change value")
	}
	if percentChange != 0.0 {
		t.Error("Incorrect percent change value")
	}
}