// Test generated by RoostGPT for test roost-test using AI Model vertex

package main

import (
	"fmt"
	"math"
	"testing"
)

func TestGetNamedStockPriceChange(t *testing.T) {
	// Test case 1: Positive change
	prevStockPrice := 100000.0
	currentStockPrice := 100001.0

	change, percentChange := getNamedStockPriceChange(prevStockPrice, currentStockPrice)

	if change != 1.0 || percentChange != 0.01 {
		t.Error("Expected change to be 1.0 and percentChange to be 0.01, but got change = %f and percentChange = %f", change, percentChange)
	}

	// Test case 2: Negative change
	prevStockPrice = 100000.0
	currentStockPrice = 99999.0

	change, percentChange = getNamedStockPriceChange(prevStockPrice, currentStockPrice)

	if change != -1.0 || percentChange != -0.01 {
		t.Error("Expected change to be -1.0 and percentChange to be -0.01, but got change = %f and percentChange = %f", change, percentChange)
	}
}

func main() {
	prevStockPrice := 100000.0
	currentStockPrice := 90000.0

	change, percentChange := getNamedStockPriceChange(prevStockPrice, currentStockPrice)

	if change < 0 {
		fmt.Printf("The Stock Price decreased by $%.2f which is %.2f%% of the prev price\n", math.Abs(change), math.Abs(percentChange))
	} else {
		fmt.Printf("The Stock Price increased by $%.2f which is %.2f%% of the prev price\n", change, percentChange)
	}
}