// Test generated by RoostGPT for test roost-test using AI Model vertex

package main

import (
	"fmt"
	"math"
	"testing"
)

func TestMain5fde9526fa(t *testing.T) {
	// Test case 1: Positive change
	prevStockPrice := 0.0
	currentStockPrice := 100000.0

	change, percentChange := getStockPriceChange(prevStockPrice, currentStockPrice)

	if change < 0 {
		t.Error("Expected change to be positive, but it was negative")
	} else if math.Abs(change) != 100000.0 {
		t.Error("Expected change to be equal to $100000.0, but it was not")
	} else if math.Abs(percentChange) != 100.0 {
		t.Error("Expected percent change to be equal to 100.0%, but it was not")
	}

	// Test case 2: Negative change
	prevStockPrice = 100000.0
	currentStockPrice = 0.0

	change, percentChange = getStockPriceChange(prevStockPrice, currentStockPrice)

	if change > 0 {
		t.Error("Expected change to be negative, but it was positive")
	} else if math.Abs(change) != 100000.0 {
		t.Error("Expected change to be equal to $100000.0, but it was not")
	} else if math.Abs(percentChange) != 100.0 {
		t.Error("Expected percent change to be equal to 100.0%, but it was not")
	}
}