// Test generated by RoostGPT for test roost-test using AI Model vertex

package main

import (
	"errors"
	"fmt"
	"math"
	"testing"
)

func TestMain600c7cf2e0(t *testing.T) {
	// Test case 1: Valid input
	prevStockPrice := 0.0
	currentStockPrice := 100000.0

	change, percentChange, err := getStockPriceChangeWithError(prevStockPrice, currentStockPrice)

	if err != nil {
		t.Error("Error should not be nil")
	} else {
		if change < 0 {
			t.Errorf("The Stock Price should have decreased")
		} else {
			t.Errorf("The Stock Price should have increased")
		}
	}

	// Test case 2: Invalid input
	prevStockPrice = -100000.0
	currentStockPrice = 0.0

	change, percentChange, err = getStockPriceChangeWithError(prevStockPrice, currentStockPrice)

	if err == nil {
		t.Error("Error should not be nil")
	}
}

func getStockPriceChangeWithError(prevStockPrice, currentStockPrice float64) (float64, float64, error) {
	if prevStockPrice < 0 {
		return 0.0, 0.0, errors.New("Invalid previous stock price")
	}

	if currentStockPrice < 0 {
		return 0.0, 0.0, errors.New("Invalid current stock price")
	}

	change := currentStockPrice - prevStockPrice
	percentChange := change / prevStockPrice * 100

	return change, percentChange, nil
}