// Test generated by RoostGPT for test roost-test using AI Model vertex

package main

import (
	"errors"
	"fmt"
	"math"
	"testing"
)

func TestGetStockPriceChangeWithError9e5237daa1(t *testing.T) {
	// Test case 1: Previous price is zero
	prevPrice := 0.0
	currentPrice := 10.0
	change, percentChange, err := getStockPriceChangeWithError(prevPrice, currentPrice)
	if err != nil {
		t.Errorf("Expected no error, but got: %v", err)
	}
	if change != 10.0 {
		t.Errorf("Expected change to be 10.0, but got: %v", change)
	}
	if percentChange != 100.0 {
		t.Errorf("Expected percentChange to be 100.0, but got: %v", percentChange)
	}

	// Test case 2: Previous price is not zero
	prevPrice = 10.0
	currentPrice = 20.0
	change, percentChange, err = getStockPriceChangeWithError(prevPrice, currentPrice)
	if err != nil {
		t.Errorf("Expected no error, but got: %v", err)
	}
	if change != 10.0 {
		t.Errorf("Expected change to be 10.0, but got: %v", change)
	}
	if percentChange != 100.0 {
		t.Errorf("Expected percentChange to be 100.0, but got: %v", percentChange)
	}
}