# Test generated by RoostGPT for test roost-test using AI Model vertex

"""
This file contains unit tests for the resetInterpreter() method.
"""

from __future__ import print_function
import sys


def resetInterpreter():
    """
    resets the interpreter mind.
    """
    global eax, ebx, ecx, edx, zeroFlag, stack
    global variables, jumps, lines, tokens, returnStack
    eax = 0
    ebx = 0
    ecx = 0
    edx = 0
    zeroFlag = False
    stack = []
    jumps = {}
    variables = {}
    lines = []
    tokens = []
    returnStack = []


# DEBUG FUNCTION
# .


def TestResetInterpreter35449d2449():
    """
    Test that the resetInterpreter() method resets all of the global variables.
    """

    # Check that all of the global variables are reset to their default values.
    assert eax == 0
    assert ebx == 0
    assert ecx == 0
    assert edx == 0
    assert zeroFlag is False
    assert stack == []
    assert jumps == {}
    assert variables == {}
    assert lines == []
    assert tokens == []
    assert returnStack == []


if __name__ == "__main__":
    """
    Run the unit tests.
    """

    t = unittest.TestLoader().loadTestsFromTestCase(TestResetInterpreter35449d2449)
    unittest.TextTestRunner(verbosity=2).run(t)